### ISSUE TITLE
Add another category to legend: Existing variants already tested in paper

### ISSUE THREAD

**Issue by AAoritz** [NickCH-K/r2especcurve#1]
Would it make sense to have three categories in the legend? 

1. Original baseline estimate 
2. Original robustness check 
3. New robustness check

**Comment by AAoritz** [comment]
Thanks for the cool package by the way!

**Comment by NickCH-K** [comment]
That sounds feasible, I'll see what I can do

**Comment by NickCH-K** [comment]
Alright, this is implemented now with 2feed7d871e8f9d6d24b351ecbe74573cd138de9 
See the new step 9 under the Stata instructions for a guide on how to use it; unfortunately the syntax is a little tricker than the rest.

**Comment by AAoritz** [comment]
Works very well! Many thanks!
