### ISSUE TITLE
Changing design of plot

### ISSUE THREAD

**Issue by mcwayrm** [NickCH-K/r2especcurve#3]
Hey @NickCH-K , I may just be an intermediate coder and there is an easy solution for this. But I wanted to change the features of the specification curve. Say replacing the y axis label. Changing the font to serif. Or (im my case) replace the choices with color blocks instead of number given I am trying to fit 378 specifications on one curve -- leading to a lot of clutter -- which would mean adding a legend for matching colors to numbers. Even for the first two (simple) edits I was struggling to modify the function. I tried adding `ggplot2` attributes with `+` to override but that did not help. And when I use `skip_theme = TRUE` this removes a lot of the great work you have already done. 

I was wondering if you could help me add these three features: 
1. Relabeling the y-axis
2. Changing the font family
3. switching out choice numbers for a color block, and adding a legend to match colors to choice numbers. 

Any help in the right direction would be appreciated!

**Comment by NickCH-K** [comment]
`spec_curve` returns what is actually two plots pasted together using the **patchwork** package. If you want to edit the underlying **ggplot2** objects, you need to set the `return_separate` option. This will give you back a list of two graphs which you can then edit.

For the y-axis and the font, you can do it like this:

```r
library(r2especcurve)

data(cholera_dat)
plots = spec_curve(cholera_dat[cholera_dat$outcome == 3,],
           decision_cols = c('analytical_decision_1','analytical_decision_2','analytical_decision_3'),
           decision_labels = c('Specification','Bandwidth','Controls'),
           orig_spec_values = c(1,1,1),
           return_separate = TRUE)

new_top_plot = plots[[1]] + 
  labs(y = 'My Label') + 
  theme(text = element_text(family = 'serif'))

# Put 'em together again
new_top_plot/plots[[2]] + patchwork::plot_layout(widths = c(1, 1), heights = c(4,1))
```

Changing to a color block is a bit trickier. You can certainly add a color block on top with

```r
plots[[2]] + geom_point(mapping = aes(color = factor(value)), shape = 15)
```

but this will not get rid of the text labels that are already there. Might work if you can size them juuuust right to block out the text behind the blocks. For this I'd recommend looking at the code for how the second plot is made (just put `spec_curve` into R, without parentheses, and it will show you source code, or look at the github code) and edit it yourself, then patch it together with plot 1 using the code I mentioned above.

**Comment by NickCH-K** [comment]
Oh right, you could just set the `font_size` to 0 to get rid of the text labels. So the below code will do everything you want. Now, that said, the legend you end up with might not fit in the area you want it, so you might need to fiddle with that. Maybe use `theme(legend.position = 'bottom')` and give hte bottom graph more vertical room in `plot_layout`?

```r
plots = spec_curve(cholera_dat[cholera_dat$outcome == 3,],
                   decision_cols = c('analytical_decision_1','analytical_decision_2','analytical_decision_3'),
                   decision_labels = c('Specification','Bandwidth','Controls'),
                   orig_spec_values = c(1,1,1),
                   return_separate = TRUE,
                   font_size = 0)

new_top_plot = plots[[1]] + 
  labs(y = 'My Label') + 
  theme(text = element_text(family = 'serif'))
new_bottom_plot = plots[[2]] + geom_point(mapping = aes(color = factor(value)), shape = 15)

new_top_plot/new_bottom_plot + patchwork::plot_layout(widths = c(1, 1), heights = c(4,1))
```

**Comment by mcwayrm** [comment]
Thanks! That did the trick and the specification curves are a lot more readable now. The quick response is really appreciated as well, and thanks for making this public resource.
